spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices_db
    username: postgres
    password: bbcstzh1
    driver-class-name: org.postgresql.Driver
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
    instance:
      prefer-ip-address: false
