spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: compani1_route
          uri: lb://compani1  # Переадресация запросов на микросервис compani_1
          predicates:
            - Path=/api/v1/compani1/**
        - id: compani2_route
          uri: lb://compani2  # Переадресация запросов на микросервис compani_2
          predicates:
            - Path=/api/v1/compani2/**
        - id: compani3_route
          uri: lb://compani3  # Переадресация запросов на микросервис compani_3
          predicates:
            - Path=/api/v1/compani3/**
        - id: compani4_route
          uri: lb://compani4  # Переадресация запросов на микросервис compani_4
          predicates:
            - Path=/api/v1/compani4/**
  rabbitmq:
    main_queue: main_queue
    exchange: exchange
    main_routing_key: main_routing_key
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
