spring:
  cloud:
    gateway:
      routes:
        - id: compani1_route
          uri: lb://COMPANI_1  # Переадресация запросов на микросервис compani_1
          predicates:
            - Path=/api/test/compani1/**
        - id: compani2_route
          uri: lb://COMPANI_2  # Переадресация запросов на микросервис compani_2
          predicates:
            - Path=/api/test/compani2/**
        - id: compani3_route
          uri: lb://COMPANI_3  # Переадресация запросов на микросервис compani_3
          predicates:
            - Path=/api/test/compani3/**
        - id: compani4_route
          uri: lb://COMPANI_4  # Переадресация запросов на микросервис compani_4
          predicates:
            - Path=/api/test/compani4/**
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

my:
  property:
    name: "Sultan"
